# $schema: ../../../schema/resticprofile.json
# https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

wiki:
  lock: "/tmp/resticprofile-profile-wiki.lock"
  status-file: backup-wiki-status.json
  repository: "s3:{{ restic_s3_endpoint }}"
  password-file: "~/.restic.password.txt"
  env:
    AWS_ACCESS_KEY_ID: "{{ restic_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic_secret_key }}"
  retention:
    after-backup: false
    keep-daily: 2
    keep-weekly: 7
    keep-monthly: 5
    keep-yearly: 2
  backup:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    option:
      - s3.storage-class=ONEZONE_IA
    run-before:
      - curl {{ wiki_healthcheck_url }}/start
      - rm -f /opt/wiki/config/backups/backup.zip || true
      - docker compose -f /opt/wiki/docker-compose.yml exec -T bookstack sh -c '/app/www/bookstack-system-cli backup /app/www/storage/backups/backup.zip'
      - docker compose -f /opt/wiki/docker-compose.yml exec -T bookstack sh -c 'chown {{ ansible_user_uid }}:{{ ansible_user_gid }} /app/www/storage/backups/backup.zip'
      - docker compose -f /opt/wiki/docker-compose.yml exec -T bookstack sh -c 'chmod 644 /config/log/logrotate.status'
    run-after:
      - curl {{ wiki_healthcheck_url }}/0
    run-after-fail:
      - curl {{ wiki_healthcheck_url }}/fail
    schedule: "03:00"
    verbose: 2
    tag:
      - hetzner
      - wiki
    source:
      - "/opt/wiki/docker-compose.yml"
      - "/opt/wiki/config"

  forget:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    keep-daily: 7
    keep-weekly: 8
    keep-monthly: 12
    keep-yearly: 10
    prune: true
    schedule: "05:00"
    schedule-permission: user

  prune:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    schedule:
      - "sun 3:30"
    schedule-permission: user

  # Verify command
  check:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    schedule: "06:00"
    schedule-permission: user

  description: Backup Bookstack {{ wiki_domain }}

  verbose: true
  cleanup-cache: true
