---
collections:
  - name: sylvainmetayer.workstation
    version: 1.2.52
  - name: devsec.hardening
    version: 10.1.0
  - name: community.sops
    version: 2.0.0
roles:
  - src: geerlingguy.certbot
    version: 5.3.0
  - src: escalate.swap
    version: v2.0.0
  - src: geerlingguy.docker
    version: 7.4.3
  - src: andrewrothstein.starship
    version: v1.2.3
