---
collections:
  - name: sylvainmetayer.workstation
    version: 1.2.38
  - name: devsec.hardening
    version: 9.0.1
  - name: community.sops
    version: 1.4.1
roles:
  - src: geerlingguy.certbot
    version: 5.0.1
  - src: geerlingguy.docker
    version: 7.3.0
  - src: andrewrothstein.starship
    version: v1.2.1
