---
collections:
  - name: sylvainmetayer.workstation
    version: 1.2.46
  - name: devsec.hardening
    version: 10.0.0
  - name: community.sops
    version: 1.9.0
roles:
  - src: geerlingguy.certbot
    version: 5.2.0
  - src: escalate.swap
    version: v2.0.0
  - src: geerlingguy.docker
    version: 7.4.1
  - src: andrewrothstein.starship
    version: v1.2.2
