---
mysql_root_password: "{{ lookup('viczem.keepass.keepass', 'infra/ansible/gibss/mysql-root', 'password') }}"
mysql_databases:
  - name: "{{ lookup('viczem.keepass.keepass', 'infra/ansible/rss-db-credentials', 'custom_properties', 'db_name') }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ lookup('viczem.keepass.keepass', 'infra/ansible/rss-db-credentials', 'username') }}"
    host: "%"
    password: "{{ lookup('viczem.keepass.keepass', 'infra/ansible/rss-db-credentials', 'password') }}"
    priv: "{{ lookup('viczem.keepass.keepass', 'infra/ansible/rss-db-credentials', 'username') }}.*:ALL"
