# sops updatekeys secrets.yaml
creation_rules:
  - key_groups:
      - age:
          - age1pvr43f8dnpsq7swgc0r3cy799yvyk2y4wj8z3n57sckq3z6dx5yq4rntuu # perso
          - age16rspnzt6j2qxa2587t6umh9qykrqu2amrr0hx9xt2z7elyky3a3q4p5s7l # pro
