# $schema: ../../../schema/resticprofile.json
# https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

monica_v4:
  lock: "/tmp/resticprofile-profile-monica_v4.lock"
  status-file: backup-monica_v4-status.json
  repository: "s3:{{ restic_s3_endpoint }}"
  password-file: "~/.restic.password.txt"
  env:
    AWS_ACCESS_KEY_ID: "{{ restic_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic_secret_key }}"
  retention:
    after-backup: true
    keep-daily: 2
    keep-weekly: 7
    keep-monthly: 5
    keep-yearly: 2
  backup:
    option:
      - s3.storage-class=ONEZONE_IA
    run-before:
      - curl {{ monica_v4_healthcheck_url }}/start
      - docker compose -f {{ monica_v4_base_path }}/docker-compose.yml exec -T monica_v4_db sh -c 'mariadb-dump -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE' > {{ monica_v4_base_path }}/dump.sql
      - docker compose -f {{ monica_v4_base_path }}/docker-compose.yml exec -T crm  sh -c 'apt update && apt install -y zip'
      - docker compose -f {{ monica_v4_base_path }}/docker-compose.yml exec -T crm  sh -c 'zip -r /tmp/backup.zip /var/www/html/storage'
      - docker compose -f {{ monica_v4_base_path }}/docker-compose.yml exec -T crm sh -c 'mv /tmp/backup.zip /var/www/html/storage/'
      - docker compose -f {{ monica_v4_base_path }}/docker-compose.yml exec -T crm sh -c 'chown {{ ansible_user_uid }}:{{ ansible_user_gid }} /var/www/html/storage/backup.zip'
    run-after:
      - curl {{ monica_v4_healthcheck_url }}/0
    run-after-fail:
      - curl {{ monica_v4_healthcheck_url }}/fail
    schedule: "03:00"
    verbose: 2
    tag:
      - hetzner
      - monica_v4
    source:
      - "{{ monica_v4_base_path }}/docker-compose.yml"
      - "{{ monica_v4_base_path }}/data/backup.zip"
      - "{{ monica_v4_base_path }}/dump.sql"
      - "{{ monica_v4_base_path }}/.env"

  forget:
    keep-daily: 7
    keep-weekly: 8
    keep-monthly: 12
    keep-yearly: 10
    prune: true
    schedule: "05:00"
    schedule-permission: user
    schedule-lock-wait: 1h

  prune:
    schedule:
      - "sun 3:30"
    schedule-permission: user
    schedule-lock-wait: 1h

  # Verify command
  check:
    schedule: "06:00"
    schedule-permission: user
    schedule-lock-wait: 1h

  description: Backup Monica V4 {{ monica_v4_domain }}

  verbose: true
  cleanup-cache: true
