---
- name: Copy photoprism service
  template:
    src: ./templates/photoprism.service.j2
    dest: ~/.config/systemd/user/photoprism.service
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0644"

#- name: Make sure photoprism service is running
#  ansible.builtin.systemd:
#    # state: started
#    state: stopped
#    daemon_reload: true
#    name: photoprism
#    scope: user
#    # enabled: true
#    enabled: false
