---
- name: Install rclone
  become: true
  ansible.builtin.package:
    name: rclone
    state: present

- name: Ensure Rclone app folder exists
  become: true
  file:
    mode: "0700"
    path: "{{ rclone_base_path }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Template rclone script
  template:
    src: ./templates/rclone.sh.j2
    dest: "{{ ansible_user_dir }}/rclone.sh"
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0744"

- name: Template rclone service
  template:
    src: ./templates/rclone.service.j2
    dest: ~/.config/systemd/user/rclone.service
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0644"

- name: Template rclone config
  template:
    src: ./templates/rclone.conf.j2
    dest: ~/.config/rclone/rclone.conf
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0600"
