---
# Source : https://unix.stackexchange.com/questions/520098/sudo-authentication-when-using-ssh-key-auth-with-keepassputty
- name: Install required packages
  ansible.builtin.package:
    name: libpam-ssh-agent-auth
    state: present

- name: Enable PAM module
  lineinfile:
    insertafter: "#%PAM-1.0"
    path: /etc/pam.d/sudo
    state: present
    line: "auth sufficient pam_ssh_agent_auth.so file=~/.ssh/authorized_keys"

- name: Ensure SSH agent is forwarded to sudo
  lineinfile:
    insertbefore: BOF
    path: /etc/sudoers
    state: present
    line: 'Defaults env_keep += "SSH_AUTH_SOCK"'
    validate: /usr/sbin/visudo -cf %s
