---

- name: Create user
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
    password: "{{ user_password | password_hash('sha512') }}"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', user_ssh_key) }}"

- name: Ensure required folder exists
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  with_items:
    - "/home/{{ user_name }}/.ssh"
    - "/home/{{ user_name }}/.config/systemd/user/"
