# $schema: ../../../schema/resticprofile.json
# https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

photoprism:
  lock: "/tmp/resticprofile-profile-photoprism.lock"
  repository: "s3:{{ restic_s3_endpoint }}"
  password-file: "~/.restic.password.txt"
  env:
    AWS_ACCESS_KEY_ID: "{{ restic_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic_secret_key }}"
  retention:
    after-backup: true
    keep-daily: 2
    keep-weekly: 7
    keep-monthly: 5
    keep-yearly: 2
  backup:
    option:
      - s3.storage-class=ONEZONE_IA
    run-before:
      - curl {{ photoprism_healthcheck_url }}/start
      - docker compose -f /opt/photoprism/docker-compose.yml exec -T photoprism sh -c "photoprism backup storage/dump.sql -f"
    run-after:
      - curl {{ photoprism_healthcheck_url }}/0
    run-after-fail:
      - curl {{ photoprism_healthcheck_url }}/fail
    schedule: "03:00"
    verbose: 2
    tag:
      - RaspberryPi
      - photoprism
    source:
      - "/opt/photoprism/docker-compose.yml"
      - "/opt/photoprism/storage"
    exclude:
      - cache/cmd/*

  forget:
    keep-daily: 7
    keep-weekly: 8
    keep-monthly: 12
    keep-yearly: 10
    prune: true
    schedule: "05:00"
    schedule-permission: user
    schedule-lock-wait: 1h

  prune:
    schedule:
      - "sun 3:30"
    schedule-permission: user
    schedule-lock-wait: 1h

  # Verify command
  check:
    schedule: "06:00"
    schedule-permission: user
    schedule-lock-wait: 1h

  description: Backup Photoprism {{ photoprism_domain }}

  verbose: true
  cleanup-cache: true
