access_key: ENC[AES256_GCM,data:F+PturRBdAeckVc7jYUilg==,iv:tjyY7cEjMvy8UbaVrXmwZlPF0zZ6DmILt02IK/RJok8=,tag:WZRUgduMiY+xujSSbkD/mA==,type:str]
secret_key: ENC[AES256_GCM,data:UNFpBfDEzNMXEGc/Kjr+7V6GOjM73fo4SUPR5MNbz4BjxxdUyCO2qw==,iv:h2XeBXH+kwI4eHuKfEVnXyYXFD1xD0a2S18hfGE7edU=,tag:8niPJxKetp7Q77QGsgD5Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pvr43f8dnpsq7swgc0r3cy799yvyk2y4wj8z3n57sckq3z6dx5yq4rntuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMDZIVCsxaGpzek1kdnpk
            YzBpb1QxdFlGWmJ0UjBnS1FLME9ZY085TkVFCmlVbzZQWWhsOFU1cDhYOWpuUXM1
            Vzd6T08rRkxmWmNiQkkrUzZLOHdxMjgKLS0tIERmMWN1RENETGV6alorR2x3YW83
            ZWwyT2lXckVrd2RJRmxnT2FrUVd6Wm8KfE/wR/OVHHHX3ZRu296KQGe+Fq/kpeVG
            gpEtiHfV1Ra8qV6f6BBlYQ1nOYSjcvilIonirptoRZagvjIM8uhKuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16rspnzt6j2qxa2587t6umh9qykrqu2amrr0hx9xt2z7elyky3a3q4p5s7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VmZ0TjBuYWcrMWRMaGlu
            ZVpkZHJaaWZmc3g3UlZSTjBZMVZyN3hZaDA0CmNJTEs4SW80S2VnM20rNHRaWm1G
            Qmw2OURxMWN3RktDRmE4NEQydlFpNGsKLS0tIDMzT09SNjI0d0Jmd2x4RW9zTlpt
            QUtqbGNPRVovUTlLVTBZMEYwQ21XQUEKStBllNFP0/h4F6qC4SU/aCkHHY4mKslc
            YZ7L1jw9kVIOSep5W5NPbSMOHkBsAZ7dFKW8+353wUB5eFyWvT6IFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T22:21:22Z"
    mac: ENC[AES256_GCM,data:6dFv4lF3M9CCHVV3JSeL5vcfTe06yrt9baUpzHvaxbLPICmnijhVt8tuJ+d8FdMklQKvo1eVAsK7JT7iIlhczhXZkSpSPBHHayfJgTP8nGV7l3ztsZ04jFTYVPR7hgwEtPkHdZJKh/45iLA/Ze1hxrL+DNYYg70Fg9sV9vDf3tY=,iv:yw1RCVMpPgRgmtcDG7sBQcjc67scbGdLgUX3M7aBVTw=,tag:ZIB1ujzXQ/4AQdcX/CXmVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
