# $schema: ../../../schema/resticprofile.json
# https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

nextcloud:
  lock: "/tmp/resticprofile-profile-nextcloud.lock"
  status-file: backup-nextcloud-status.json
  repository: "s3:{{ restic_s3_endpoint }}"
  password-file: "~/.restic.password.txt"
  env:
    AWS_ACCESS_KEY_ID: "{{ restic_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic_secret_key }}"
  retention:
    after-backup: true
    keep-daily: 2
    keep-weekly: 7
    keep-monthly: 5
    keep-yearly: 2
  backup:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    option:
      - s3.storage-class=ONEZONE_IA
    run-before:
      - curl {{ nextcloud_healthcheck_url }}/start
      - docker compose -f /opt/nextcloud/docker-compose.yml exec -T db sh -c 'mariadb-dump -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE' > /opt/nextcloud/dump.sql
    run-after:
      - curl {{ nextcloud_healthcheck_url }}/0
    run-after-fail:
      - curl {{ nextcloud_healthcheck_url }}/fail
    schedule: "03:00"
    verbose: 2
    tag:
      - hetzner
      - nextcloud
    source:
      - "/opt/nextcloud/docker-compose.yml"
      - "/opt/nextcloud/dump.sql"
      - "/opt/nextcloud/config"
      - "/opt/nextcloud/data"

  forget:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    keep-daily: 7
    keep-weekly: 8
    keep-monthly: 12
    keep-yearly: 10
    prune: true
    schedule: "05:00"
    schedule-permission: user

  prune:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    schedule:
      - "sun 3:30"
    schedule-permission: user

  # Verify command
  check:
    schedule-lock-mode: fail
    retry-lock: 2m
    schedule-lock-wait: 1h
    schedule: "06:00"
    schedule-permission: user

  description: Backup Nextcloud {{ nextcloud_domain }}

  verbose: true
  cleanup-cache: true
