---
certbot_auto_renew: true
certbot_auto_renew_user: "root"
certbot_auto_renew_hour: "4"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade --renew-hook 'service nginx reload'"
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: "certs@sylvain.dev"

certbot_create_standalone_stop_services:
  - nginx
