---
- name: Copy wiki service
  template:
    src: ./templates/wiki.service.j2
    dest: ~/.config/systemd/user/wiki.service
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0644"

- name: Make sure wiki service is running
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: wiki
    scope: user
    enabled: true
