on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

name: "Daily"

jobs:
  checkAsdfUpdatesOpentofu:
    name: "ASDF Update terraform"

    uses: ./.github/workflows/part_asdf_update.yml
    with:
      plugin: "opentofu"
      constraint: "1"
